version: 2.1

orbs:
  cache: compute/cache@0.0.3
  node: circleci/node@2

jobs:
  test-clj:
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.536

    steps:
      - checkout

      - cache/clj:
          steps:
            - run:
               - name: Run CLJ Tests
               - command: clojure -A:test

  test-cljs:
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.536-node-browsers

    steps:
      - checkout

      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install

      - run:
          name: Run CLJS Karma Tests
          command: |
            npx shadow-cljs -v compile test-ci
            npx karma start --single-run

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test-clj
      - test-cljs