version: 2.1

defaults: &defaults
  docker:
    - image: circleci/clojure:tools-deps-1.9.0.397-node-browsers

orbs:
  cache: compute/cache@0.0.3

jobs:
  test-clj:
    <<: *defaults

    steps:
      - checkout

      - cache/clj:
          steps:
            - run:
               - name: Run CLJ Tests
               - command: clojure -A:test

  test-cljs:
    <<: *defaults

    steps:
      - checkout

      - run: npm init -y
      - run: npm install

      - cache/cljs:
          steps:
            - run:
                - name: Run CLJS Karma Tests
                - command: |
                    npx shadow-cljs -v compile test-ci
                    npx karma start --single-run

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test-clj
      - test-cljs